name: baqaya_alkhayr
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc:
    ^8.1.3
    # direction of app (ar, en..)
  flutter_localization: ^0.1.14
  equatable: ^2.0.5
  flutter_svg: ^2.0.8
  shared_preferences: ^2.2.2
  pie_chart: 5.3.2
  carousel_slider: 4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
