import 'models/machine.dart';

List<Machine> machines = [
  Machine(
    id: "6",
    isAvailable: false,
    location: "الدمام - العدامة",
    capacity: 48,
    destination: 18,
    samad: 60,
    alaf: 15,
  ),
  Machine(
    id: "4",
    isAvailable: true,
    location: "الرياض - الملز",
    capacity: 50,
    destination: 10,
    samad: 30,
    alaf: 65,
  ),
  Machine(
    id: "8",
    isAvailable: true,
    location: "المدينة المنورة - الرسالة",
    capacity: 55,
    destination: 12,
    samad: 36,
    alaf: 72,
  ),
  Machine(
    id: "9",
    isAvailable: false,
    location: "الطائف - الحوية",
    capacity: 38,
    destination: 9,
    samad: 26,
    alaf: 50,
  ),
  Machine(
    id: "18",
    isAvailable: true,
    location: "عسير - أبها",
    capacity: 53,
    destination: 13,
    samad: 39,
    alaf: 60,
  ),
  Machine(
    id: "16",
    isAvailable: true,
    location: "حائل - البدع",
    capacity: 49,
    destination: 16,
    samad: 54,
    alaf: 21,
  ),
  Machine(
    id: "10",
    isAvailable: true,
    location: "الخبر - الظهران",
    capacity: 44,
    destination: 14,
    samad: 55,
    alaf: 19,
  ),
  Machine(
    id: "17",
    isAvailable: false,
    location: "نجران - الفيصلية",
    capacity: 37,
    destination: 8,
    samad: 47,
    alaf: 25,
  ),
  Machine(
    id: "20",
    isAvailable: true,
    location: "الجوف - سكاكا",
    capacity: 45,
    destination: 10,
    samad: 52,
    alaf: 18,
  ),
  Machine(
    id: "13",
    isAvailable: true,
    location: "الأحساء - النزهة",
    capacity: 30,
    destination: 6,
    samad: 49,
    alaf: 23,
  ),
  Machine(
    id: "14",
    isAvailable: true,
    location: "تبوك - الخالدية",
    capacity: 52,
    destination: 11,
    samad: 33,
    alaf: 68,
  ),
  Machine(
    id: "15",
    isAvailable: false,
    location: "جيزان - الراحة",
    capacity: 36,
    destination: 7,
    samad: 42,
    alaf: 29,
  ),
  Machine(
    id: "11",
    isAvailable: true,
    location: "القصيم - بريدة",
    capacity: 33,
    destination: 8,
    samad: 37,
    alaf: 31,
  ),
  Machine(
    id: "5",
    isAvailable: true,
    location: "جدة - البلد",
    capacity: 35,
    destination: 5,
    samad: 22,
    alaf: 40,
  ),
  Machine(
    id: "7",
    isAvailable: true,
    location: "مكة  - العزيزية",
    capacity: 40,
    destination: 7,
    samad: 44,
    alaf: 28,
  ),
  Machine(
    id: "12",
    isAvailable: true,
    location: "الجبيل - الفاخرية",
    capacity: 60,
    destination: 20,
    samad: 70,
    alaf: 10,
  ),
  Machine(
    id: "19",
    isAvailable: false,
    location: "عنيزة - القيم",
    capacity: 34,
    destination: 6,
    samad: 31,
    alaf: 46,
  ),
];
